name: tbs_detector
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  camera: ^0.11.2
  flutter:
    sdk: flutter
  google_mlkit_object_detection: ^0.15.0
  image: ^4.7.2
  image_picker: ^1.2.0
  lottie: ^3.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/models/
